### ISSUE TITLE
[Vue warn]: Unknown custom element: <vue-chatbox> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by msouidi309** [sriramveeraghanta/vue-chatbox#1]
</vue-chatbox>
Hi, i installed the module but it doesn't work , 
i installed it using 'npm install --save vue-chatbox' and then i added 
"import VueChatbox from 'vue-chatbox'
Vue.use(VueChatbox)" in my main.js.
And then i put it in my App.vue file like a normal component

Anything i made wrong ? 
Thanks

**Comment by sriramveeraghanta** [comment]
Hello, msouidi,
It is still under development. There will be a working prototype beta release with in 5 days. Please check release milestones
